import type {
  User,
  Section,
  Product,
  GoldPrice,
  PromoCode,
} from '../types';

// Mock Users
export const mockUsers = {
  user: {
    id: '1',
    email: 'user@example.com',
    name: 'John Doe',
    role: 'user',
    avatar: 'https://i.pravatar.cc/150?img=1',
    createdAt: new Date('2024-01-15'),
    updatedAt: new Date('2024-01-15'),
  } as User,
  admin: {
    id: '2',
    email: 'admin@example.com',
    name: 'Admin User',
    role: 'admin',
    avatar: 'https://i.pravatar.cc/150?img=2',
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
  } as User,
};

// Mock Gold Price
export const mockGoldPrice: GoldPrice = {
  id: 'gold-1',
  pricePerGram: 6500, // Price in INR per gram (adjust to your currency)
  lastUpdated: new Date('2024-04-15'),
  updatedBy: '2',
};

// Mock Sections and Subsections
export const mockSections: Section[] = [
  {
    id: 'sec-1',
    name: 'Rings',
    description: 'Elegant rings for every occasion',
    image: 'https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?w=500',
    subsections: [
      {
        id: 'sub-1-1',
        name: 'Engagement Rings',
        description: 'Timeless engagement rings',
        sectionId: 'sec-1',
      },
      {
        id: 'sub-1-2',
        name: 'Wedding Rings',
        description: 'Classic wedding bands',
        sectionId: 'sec-1',
      },
      {
        id: 'sub-1-3',
        name: 'Statement Rings',
        description: 'Bold and beautiful statement pieces',
        sectionId: 'sec-1',
      },
    ],
  },
  {
    id: 'sec-2',
    name: 'Necklaces',
    description: 'Beautiful necklaces and chains',
    image: 'https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?w=500',
    subsections: [
      {
        id: 'sub-2-1',
        name: 'Pendant Necklaces',
        description: 'Elegant pendants',
        sectionId: 'sec-2',
      },
      {
        id: 'sub-2-2',
        name: 'Chain Necklaces',
        description: 'Pure gold chains',
        sectionId: 'sec-2',
      },
      {
        id: 'sub-2-3',
        name: 'Layered Necklaces',
        description: 'Trendy layered styles',
        sectionId: 'sec-2',
      },
    ],
  },
  {
    id: 'sec-3',
    name: 'Earrings',
    description: 'Stunning earrings collection',
    image: 'https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?w=500',
    subsections: [
      {
        id: 'sub-3-1',
        name: 'Stud Earrings',
        description: 'Classic stud designs',
        sectionId: 'sec-3',
      },
      {
        id: 'sub-3-2',
        name: 'Drop Earrings',
        description: 'Elegant drop styles',
        sectionId: 'sec-3',
      },
      {
        id: 'sub-3-3',
        name: 'Hoop Earrings',
        description: 'Timeless hoops',
        sectionId: 'sec-3',
      },
    ],
  },
  {
    id: 'sec-4',
    name: 'Bracelets',
    description: 'Exquisite bracelet collection',
    image: 'https://images.unsplash.com/photo-1515562141207-6811bcb33ce8?w=500',
    subsections: [
      {
        id: 'sub-4-1',
        name: 'Gold Bracelets',
        description: 'Pure gold bracelets',
        sectionId: 'sec-4',
      },
      {
        id: 'sub-4-2',
        name: 'Charm Bracelets',
        description: 'Personalized charm options',
        sectionId: 'sec-4',
      },
      {
        id: 'sub-4-3',
        name: 'Bangle Bracelets',
        description: 'Traditional and modern bangles',
        sectionId: 'sec-4',
      },
    ],
  },
  {
    id: 'sec-5',
    name: 'Sets',
    description: 'Complete jewelry sets',
    image: 'https://images.unsplash.com/photo-1611591437281-460bfbe1220a?w=500',
    subsections: [
      {
        id: 'sub-5-1',
        name: 'Bridal Sets',
        description: 'Complete bridal jewelry',
        sectionId: 'sec-5',
      },
      {
        id: 'sub-5-2',
        name: 'Daily Wear Sets',
        description: 'Casual everyday sets',
        sectionId: 'sec-5',
      },
      {
        id: 'sub-5-3',
        name: 'Party Sets',
        description: 'Festive occasion sets',
        sectionId: 'sec-5',
      },
    ],
  },
];

// Mock Products
export const mockProducts: Product[] = [
  {
    id: 'prod-1',
    name: 'Classic Engagement Ring',
    description: 'A timeless engagement ring crafted in 22K gold with a brilliant solitaire diamond and luxurious polished finish.',
    images: [
      'https://images.unsplash.com/photo-1522312346375-d1a52e2b99b3?auto=format&fit=crop&w=900&q=80',
      'https://images.unsplash.com/photo-1499971635179-8373e2fabead?auto=format&fit=crop&w=900&q=80',
      'https://images.unsplash.com/photo-1504639725590-34d0984388bd?auto=format&fit=crop&w=900&q=80',
    ],
    sectionId: 'sec-1',
    subsectionId: 'sub-1-1',
    goldWeight: 3.5,
    makingCharge: { type: 'percentage', value: 12 },
    basePrice: 5000,
    currentPrice: 27775, // Will be calculated
    quantity: 10,
    rating: 4.8,
    reviews: 24,
    highlights: [
      'Brilliant solitaire centerpiece for timeless elegance',
      'Polished 22K gold band built for comfort and shine',
      'Perfect choice for proposals, anniversaries, and special moments',
    ],
    material: '22K Gold',
    purity: '91.6% (22K)',
    collection: 'Bridal Elegance',
    occasion: 'Engagement & Anniversary',
    specifications: {
      'Gold Weight': '3.5 g',
      'Diamond Weight': '0.50 ct',
      Finish: 'Mirror Polish',
      Warranty: '1 Year',
      Seller: 'Luxury Jewelry Co.',
    },
    createdAt: new Date('2024-02-01'),
    updatedAt: new Date('2024-02-01'),
  },
  {
    id: 'prod-2',
    name: 'Gold Wedding Band',
    description: 'A premium 22K gold wedding band designed for modern couples, with a refined satin finish and elegant comfort fit.',
    images: [
      'https://images.unsplash.com/photo-1515377905703-c511b6b50f4e?auto=format&fit=crop&w=900&q=80',
      'https://images.unsplash.com/photo-1496055417576-5af7b6d8d3d3?auto=format&fit=crop&w=900&q=80',
      'https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?auto=format&fit=crop&w=900&q=80',
    ],
    sectionId: 'sec-1',
    subsectionId: 'sub-1-2',
    goldWeight: 4.0,
    makingCharge: { type: 'fixed', value: 2000 },
    basePrice: 0,
    currentPrice: 28000, // Will be calculated
    quantity: 15,
    rating: 4.9,
    reviews: 45,
    highlights: [
      'Comfort-fit interior for daily wear',
      'Elegant satin finish with subtle shine',
      'Designed for timeless wedding presentations',
    ],
    material: '22K Gold',
    purity: '91.6% (22K)',
    collection: 'Forever Rings',
    occasion: 'Wedding',
    specifications: {
      'Gold Weight': '4.0 g',
      Finish: 'Satin',
      Width: '5 mm',
      Warranty: '1 Year',
      Seller: 'Luxury Jewelry Co.',
    },
    createdAt: new Date('2024-02-05'),
    updatedAt: new Date('2024-02-05'),
  },
  {
    id: 'prod-3',
    name: 'Statement Cocktail Ring',
    description: 'Bold cocktail ring finished in radiant gold with a show-stopping gemstone accent for evening and party luxury.',
    images: [
      'https://images.unsplash.com/photo-1511993226957-678bf0355d4f?auto=format&fit=crop&w=900&q=80',
      'https://images.unsplash.com/photo-1515832460008-370201a6320c?auto=format&fit=crop&w=900&q=80',
      'https://images.unsplash.com/photo-1522312346375-d1a52e2b99b3?auto=format&fit=crop&w=900&q=80',
    ],
    sectionId: 'sec-1',
    subsectionId: 'sub-1-3',
    goldWeight: 5.0,
    makingCharge: { type: 'percentage', value: 15 },
    basePrice: 8000,
    currentPrice: 40500, // Will be calculated
    quantity: 5,
    rating: 4.7,
    reviews: 18,
    highlights: [
      'Statement design with premium gemstone accents',
      'Highly polished gold finish for evening elegance',
      'Perfect for parties, dinners, and festive occasions',
    ],
    material: '22K Gold',
    purity: '91.6% (22K)',
    collection: 'Evening Grandeur',
    occasion: 'Party & Celebration',
    specifications: {
      'Gold Weight': '5.0 g',
      'Stone Type': 'Lab-Created Gemstone',
      Finish: 'High Polish',
      Warranty: '1 Year',
      Seller: 'Luxury Jewelry Co.',
    },
    createdAt: new Date('2024-02-10'),
    updatedAt: new Date('2024-02-10'),
  },
  {
    id: 'prod-4',
    name: 'Pendant Necklace Gold',
    description: 'An elegant gold pendant necklace with crafted detailing, perfect for daily luxury and layered styling.',
    images: [
      'https://images.unsplash.com/photo-1522312346375-d1a52e2b99b3?auto=format&fit=crop&w=900&q=80',
      'https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?auto=format&fit=crop&w=900&q=80',
      'https://images.unsplash.com/photo-15033948849-28bba6fbd13e?auto=format&fit=crop&w=900&q=80',
    ],
    sectionId: 'sec-2',
    subsectionId: 'sub-2-1',
    goldWeight: 6.0,
    makingCharge: { type: 'percentage', value: 10 },
    basePrice: 3000,
    currentPrice: 42900, // Will be calculated
    quantity: 12,
    rating: 4.6,
    reviews: 32,
    highlights: [
      'Delicate pendant with premium polished finish',
      'Lightweight and comfortable for everyday elegance',
      'Perfect for gifting and layered necklace looks',
    ],
    material: '22K Gold',
    purity: '91.6% (22K)',
    collection: 'Signature Pendants',
    occasion: 'Everyday Wear',
    specifications: {
      'Gold Weight': '6.0 g',
      'Chain Length': '18 inches',
      Finish: 'Polished',
      Warranty: '1 Year',
      Seller: 'Luxury Jewelry Co.',
    },
    createdAt: new Date('2024-02-15'),
    updatedAt: new Date('2024-02-15'),
  },
  {
    id: 'prod-5',
    name: 'Pure Gold Chain',
    description: 'A premium 22K gold chain with a smooth finish and flattering weight, designed for timeless style and daily grace.',
    images: [
      'https://images.unsplash.com/photo-1519681393784-d120267933ba?auto=format&fit=crop&w=900&q=80',
      'https://images.unsplash.com/photo-1522312346375-d1a52e2b99b3?auto=format&fit=crop&w=900&q=80',
      'https://images.unsplash.com/photo-1503341455253-b2e723bb3dbb?auto=format&fit=crop&w=900&q=80',
    ],
    sectionId: 'sec-2',
    subsectionId: 'sub-2-2',
    goldWeight: 8.0,
    makingCharge: { type: 'fixed', value: 1500 },
    basePrice: 0,
    currentPrice: 53500, // Will be calculated
    quantity: 20,
    rating: 5,
    reviews: 58,
    highlights: [
      'Smooth 22K gold chain for timeless layering',
      'Rich shine and premium weight for quality feel',
      'Ideal for pairing with pendants or wearing alone',
    ],
    material: '22K Gold',
    purity: '91.6% (22K)',
    collection: 'Everyday Classics',
    occasion: 'Daily Wear',
    specifications: {
      'Gold Weight': '8.0 g',
      'Chain Style': 'Cable',
      Finish: 'Polished',
      Warranty: '1 Year',
      Seller: 'Luxury Jewelry Co.',
    },
    createdAt: new Date('2024-02-20'),
    updatedAt: new Date('2024-02-20'),
  },
  {
    id: 'prod-6',
    name: 'Diamond Stud Earrings',
    description: 'Classic gold and diamond stud earrings designed to deliver understated luxury and sparkle for every occasion.',
    images: [
      'https://images.unsplash.com/photo-1541745537413-6bb6f68ba1c3?auto=format&fit=crop&w=900&q=80',
      'https://images.unsplash.com/photo-1529400971008-f566de0e6dfc?auto=format&fit=crop&w=900&q=80',
      'https://images.unsplash.com/photo-1503342217505-b0a15ec3261c?auto=format&fit=crop&w=900&q=80',
    ],
    sectionId: 'sec-3',
    subsectionId: 'sub-3-1',
    goldWeight: 2.5,
    makingCharge: { type: 'percentage', value: 18 },
    basePrice: 6000,
    currentPrice: 22225, // Will be calculated
    quantity: 8,
    rating: 4.9,
    reviews: 41,
    highlights: [
      'Timeless studs with brilliant-cut diamonds',
      'Lightweight design for comfortable wear',
      'Perfect for gifting and everyday elegance',
    ],
    material: '22K Gold',
    purity: '91.6% (22K)',
    collection: 'Diamond Luxe',
    occasion: 'Formal & Everyday',
    specifications: {
      'Gold Weight': '2.5 g',
      'Diamond Weight': '0.30 ct',
      Finish: 'Polished',
      Warranty: '1 Year',
      Seller: 'Luxury Jewelry Co.',
    },
    createdAt: new Date('2024-02-25'),
    updatedAt: new Date('2024-02-25'),
  },
  {
    id: 'prod-7',
    name: 'Gold Bangle Set',
    description: 'A traditional gold bangle set with intricate detailing, finished in premium 22K gold for festive and wedding occasions.',
    images: [
      'https://images.unsplash.com/photo-1515562141207-6811bcb33ce8?auto=format&fit=crop&w=900&q=80',
      'https://images.unsplash.com/photo-1503342217505-b0a15ec3261c?auto=format&fit=crop&w=900&q=80',
      'https://images.unsplash.com/photo-1529400971008-f566de0e6dfc?auto=format&fit=crop&w=900&q=80',
    ],
    sectionId: 'sec-4',
    subsectionId: 'sub-4-1',
    goldWeight: 12.0,
    makingCharge: { type: 'percentage', value: 8 },
    basePrice: 2000,
    currentPrice: 80240, // Will be calculated
    quantity: 6,
    rating: 4.8,
    reviews: 22,
    highlights: [
      'Traditional bangle set with rich gold finish',
      'Intricate detailing for an elegant look',
      'Perfect for weddings and festive wear',
    ],
    material: '22K Gold',
    purity: '91.6% (22K)',
    collection: 'Festive Heritage',
    occasion: 'Wedding & Festivals',
    specifications: {
      'Gold Weight': '12.0 g',
      'Bangle Width': '4 mm',
      Finish: 'Polished',
      Warranty: '1 Year',
      Seller: 'Luxury Jewelry Co.',
    },
    createdAt: new Date('2024-03-01'),
    updatedAt: new Date('2024-03-01'),
  },
  {
    id: 'prod-8',
    name: 'Bridal Jewelry Set',
    description: 'A complete bridal set featuring necklace, earrings, and maang tikka in rich 22K gold with ornate craftsmanship.',
    images: [
      'https://images.unsplash.com/photo-1611591437281-460bfbe1220a?auto=format&fit=crop&w=900&q=80',
      'https://images.unsplash.com/photo-1503341455253-b2e723bb3dbb?auto=format&fit=crop&w=900&q=80',
      'https://images.unsplash.com/photo-1519681393784-d120267933ba?auto=format&fit=crop&w=900&q=80',
    ],
    sectionId: 'sec-5',
    subsectionId: 'sub-5-1',
    goldWeight: 25.0,
    makingCharge: { type: 'percentage', value: 10 },
    basePrice: 15000,
    currentPrice: 178250, // Will be calculated
    quantity: 3,
    rating: 5,
    reviews: 15,
    highlights: [
      'Complete bridal ensemble with luxurious details',
      'Crafted for ceremonial elegance and heirloom styling',
      'Ideal for wedding day and special celebrations',
    ],
    material: '22K Gold',
    purity: '91.6% (22K)',
    collection: 'Royal Bride',
    occasion: 'Bridal & Wedding',
    specifications: {
      'Gold Weight': '25.0 g',
      'Includes': 'Necklace, Earrings, Maang Tikka',
      Finish: 'Ornate Polished',
      Warranty: '1 Year',
      Seller: 'Luxury Jewelry Co.',
    },
    createdAt: new Date('2024-03-05'),
    updatedAt: new Date('2024-03-05'),
  },
  {
    id: 'prod-9',
    name: 'Diamond Promise Ring',
    description: 'A delicate promise ring featuring a sparkling diamond in a minimalist gold setting, perfect for meaningful commitments.',
    images: [
      'https://images.unsplash.com/photo-1605100804763-247f67b3557e?auto=format&fit=crop&w=900&q=80',
      'https://images.unsplash.com/photo-1522312346375-d1a52e2b99b3?auto=format&fit=crop&w=900&q=80',
      'https://images.unsplash.com/photo-1496055417576-5af7b6d8d3d3?auto=format&fit=crop&w=900&q=80',
    ],
    sectionId: 'sec-1',
    subsectionId: 'sub-1-1',
    goldWeight: 2.0,
    makingCharge: { type: 'percentage', value: 20 },
    basePrice: 4000,
    currentPrice: 17800, // Will be calculated
    quantity: 8,
    rating: 4.7,
    reviews: 19,
    highlights: [
      'Delicate design with brilliant diamond centerpiece',
      'Comfortable fit for everyday wear',
      'Perfect for promises, anniversaries, and special moments',
    ],
    material: '22K Gold',
    purity: '91.6% (22K)',
    collection: 'Promise Collection',
    occasion: 'Anniversary & Promise',
    specifications: {
      'Gold Weight': '2.0 g',
      'Diamond Weight': '0.25 ct',
      Finish: 'Polished',
      Warranty: '1 Year',
      Seller: 'Luxury Jewelry Co.',
    },
    createdAt: new Date('2024-03-10'),
    updatedAt: new Date('2024-03-10'),
  },
  {
    id: 'prod-10',
    name: 'Vintage Style Ring',
    description: 'A vintage-inspired ring with intricate filigree work and a central gemstone, blending classic elegance with modern appeal.',
    images: [
      'https://images.unsplash.com/photo-1511993226957-678bf0355d4f?auto=format&fit=crop&w=900&q=80',
      'https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?auto=format&fit=crop&w=900&q=80',
      'https://images.unsplash.com/photo-1503342217505-b0a15ec3261c?auto=format&fit=crop&w=900&q=80',
    ],
    sectionId: 'sec-1',
    subsectionId: 'sub-1-3',
    goldWeight: 4.5,
    makingCharge: { type: 'percentage', value: 14 },
    basePrice: 6000,
    currentPrice: 34635, // Will be calculated
    quantity: 6,
    rating: 4.8,
    reviews: 27,
    highlights: [
      'Vintage filigree design with modern gemstone',
      'Intricate craftsmanship for heirloom quality',
      'Perfect for collectors and vintage lovers',
    ],
    material: '22K Gold',
    purity: '91.6% (22K)',
    collection: 'Heritage Collection',
    occasion: 'Special Occasions',
    specifications: {
      'Gold Weight': '4.5 g',
      'Stone Type': 'Lab-Created Gemstone',
      Finish: 'Antique Polish',
      Warranty: '1 Year',
      Seller: 'Luxury Jewelry Co.',
    },
    createdAt: new Date('2024-03-15'),
    updatedAt: new Date('2024-03-15'),
  },
  {
    id: 'prod-11',
    name: 'Layered Gold Necklace',
    description: 'A trendy layered necklace set featuring multiple chains of varying lengths, perfect for creating a personalized look.',
    images: [
      'https://images.unsplash.com/photo-1519681393784-d120267933ba?auto=format&fit=crop&w=900&q=80',
      'https://images.unsplash.com/photo-1522312346375-d1a52e2b99b3?auto=format&fit=crop&w=900&q=80',
      'https://images.unsplash.com/photo-1503341455253-b2e723bb3dbb?auto=format&fit=crop&w=900&q=80',
    ],
    sectionId: 'sec-2',
    subsectionId: 'sub-2-3',
    goldWeight: 10.0,
    makingCharge: { type: 'fixed', value: 2500 },
    basePrice: 0,
    currentPrice: 70000, // Will be calculated
    quantity: 10,
    rating: 4.6,
    reviews: 33,
    highlights: [
      'Multiple chain lengths for versatile styling',
      'Premium gold quality with smooth finish',
      'Perfect for layering with pendants',
    ],
    material: '22K Gold',
    purity: '91.6% (22K)',
    collection: 'Modern Layers',
    occasion: 'Daily Wear',
    specifications: {
      'Gold Weight': '10.0 g',
      'Chain Lengths': '16", 18", 20"',
      Finish: 'Polished',
      Warranty: '1 Year',
      Seller: 'Luxury Jewelry Co.',
    },
    createdAt: new Date('2024-03-20'),
    updatedAt: new Date('2024-03-20'),
  },
  {
    id: 'prod-12',
    name: 'Heart Pendant Necklace',
    description: 'A romantic heart-shaped pendant necklace in pure gold, symbolizing love and affection for special occasions.',
    images: [
      'https://images.unsplash.com/photo-15033948849-28bba6fbd13e?auto=format&fit=crop&w=900&q=80',
      'https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?auto=format&fit=crop&w=900&q=80',
      'https://images.unsplash.com/photo-1515562141207-6811bcb33ce8?auto=format&fit=crop&w=900&q=80',
    ],
    sectionId: 'sec-2',
    subsectionId: 'sub-2-1',
    goldWeight: 3.5,
    makingCharge: { type: 'percentage', value: 12 },
    basePrice: 2000,
    currentPrice: 25725, // Will be calculated
    quantity: 15,
    rating: 4.9,
    reviews: 42,
    highlights: [
      'Classic heart design with polished finish',
      'Delicate and meaningful for gifting',
      'Perfect for anniversaries and romantic occasions',
    ],
    material: '22K Gold',
    purity: '91.6% (22K)',
    collection: 'Romantic Hearts',
    occasion: 'Anniversary & Valentine',
    specifications: {
      'Gold Weight': '3.5 g',
      'Chain Length': '18 inches',
      Finish: 'High Polish',
      Warranty: '1 Year',
      Seller: 'Luxury Jewelry Co.',
    },
    createdAt: new Date('2024-03-25'),
    updatedAt: new Date('2024-03-25'),
  },
  {
    id: 'prod-13',
    name: 'Drop Diamond Earrings',
    description: 'Elegant drop earrings featuring sparkling diamonds in gold settings, perfect for adding sophistication to any outfit.',
    images: [
      'https://images.unsplash.com/photo-1541745537413-6bb6f68ba1c3?auto=format&fit=crop&w=900&q=80',
      'https://images.unsplash.com/photo-1529400971008-f566de0e6dfc?auto=format&fit=crop&w=900&q=80',
      'https://images.unsplash.com/photo-1503342217505-b0a15ec3261c?auto=format&fit=crop&w=900&q=80',
    ],
    sectionId: 'sec-3',
    subsectionId: 'sub-3-2',
    goldWeight: 4.0,
    makingCharge: { type: 'percentage', value: 16 },
    basePrice: 8000,
    currentPrice: 34640, // Will be calculated
    quantity: 7,
    rating: 4.8,
    reviews: 29,
    highlights: [
      'Graceful drop design with diamond accents',
      'Comfortable fit for all-day wear',
      'Ideal for formal events and special occasions',
    ],
    material: '22K Gold',
    purity: '91.6% (22K)',
    collection: 'Elegant Drops',
    occasion: 'Formal & Evening',
    specifications: {
      'Gold Weight': '4.0 g',
      'Diamond Weight': '0.40 ct',
      'Drop Length': '2.5 cm',
      Warranty: '1 Year',
      Seller: 'Luxury Jewelry Co.',
    },
    createdAt: new Date('2024-03-30'),
    updatedAt: new Date('2024-03-30'),
  },
  {
    id: 'prod-14',
    name: 'Gold Hoop Earrings',
    description: 'Classic gold hoop earrings with a modern twist, featuring a comfortable fit and timeless appeal.',
    images: [
      'https://images.unsplash.com/photo-1503342217505-b0a15ec3261c?auto=format&fit=crop&w=900&q=80',
      'https://images.unsplash.com/photo-1529400971008-f566de0e6dfc?auto=format&fit=crop&w=900&q=80',
      'https://images.unsplash.com/photo-1541745537413-6bb6f68ba1c3?auto=format&fit=crop&w=900&q=80',
    ],
    sectionId: 'sec-3',
    subsectionId: 'sub-3-3',
    goldWeight: 6.0,
    makingCharge: { type: 'fixed', value: 1800 },
    basePrice: 0,
    currentPrice: 41400, // Will be calculated
    quantity: 12,
    rating: 4.7,
    reviews: 38,
    highlights: [
      'Timeless hoop design with modern comfort',
      'Versatile for casual and formal wear',
      'Perfect for building a jewelry collection',
    ],
    material: '22K Gold',
    purity: '91.6% (22K)',
    collection: 'Classic Hoops',
    occasion: 'Everyday & Formal',
    specifications: {
      'Gold Weight': '6.0 g',
      'Hoop Diameter': '3 cm',
      Finish: 'Polished',
      Warranty: '1 Year',
      Seller: 'Luxury Jewelry Co.',
    },
    createdAt: new Date('2024-04-05'),
    updatedAt: new Date('2024-04-05'),
  },
  {
    id: 'prod-15',
    name: 'Charm Bracelet',
    description: 'A customizable charm bracelet featuring various gold charms, perfect for creating a personal story through jewelry.',
    images: [
      'https://images.unsplash.com/photo-1515562141207-6811bcb33ce8?auto=format&fit=crop&w=900&q=80',
      'https://images.unsplash.com/photo-1503342217505-b0a15ec3261c?auto=format&fit=crop&w=900&q=80',
      'https://images.unsplash.com/photo-1529400971008-f566de0e6dfc?auto=format&fit=crop&w=900&q=80',
    ],
    sectionId: 'sec-4',
    subsectionId: 'sub-4-2',
    goldWeight: 8.0,
    makingCharge: { type: 'percentage', value: 11 },
    basePrice: 5000,
    currentPrice: 58880, // Will be calculated
    quantity: 9,
    rating: 4.9,
    reviews: 31,
    highlights: [
      'Personalized charm collection for storytelling',
      'Expandable design for adding more charms',
      'Perfect for gifts and self-expression',
    ],
    material: '22K Gold',
    purity: '91.6% (22K)',
    collection: 'Personal Stories',
    occasion: 'Everyday & Gifts',
    specifications: {
      'Gold Weight': '8.0 g',
      'Chain Length': '7 inches',
      'Included Charms': '3 Gold Charms',
      Warranty: '1 Year',
      Seller: 'Luxury Jewelry Co.',
    },
    createdAt: new Date('2024-04-10'),
    updatedAt: new Date('2024-04-10'),
  },
  {
    id: 'prod-16',
    name: 'Traditional Kada',
    description: 'An authentic traditional kada bracelet with intricate patterns, symbolizing prosperity and cultural heritage.',
    images: [
      'https://images.unsplash.com/photo-1503341455253-b2e723bb3dbb?auto=format&fit=crop&w=900&q=80',
      'https://images.unsplash.com/photo-1519681393784-d120267933ba?auto=format&fit=crop&w=900&q=80',
      'https://images.unsplash.com/photo-1522312346375-d1a52e2b99b3?auto=format&fit=crop&w=900&q=80',
    ],
    sectionId: 'sec-4',
    subsectionId: 'sub-4-3',
    goldWeight: 15.0,
    makingCharge: { type: 'percentage', value: 9 },
    basePrice: 3000,
    currentPrice: 103350, // Will be calculated
    quantity: 5,
    rating: 4.8,
    reviews: 26,
    highlights: [
      'Traditional design with cultural significance',
      'Intricate craftsmanship and premium finish',
      'Perfect for festivals and special ceremonies',
    ],
    material: '22K Gold',
    purity: '91.6% (22K)',
    collection: 'Cultural Heritage',
    occasion: 'Festivals & Ceremonies',
    specifications: {
      'Gold Weight': '15.0 g',
      'Design': 'Traditional Kada',
      Finish: 'Polished',
      Warranty: '1 Year',
      Seller: 'Luxury Jewelry Co.',
    },
    createdAt: new Date('2024-04-15'),
    updatedAt: new Date('2024-04-15'),
  },
  {
    id: 'prod-17',
    name: 'Daily Wear Jewelry Set',
    description: 'A practical daily wear set including necklace, earrings, and bracelet in matching gold designs for everyday elegance.',
    images: [
      'https://images.unsplash.com/photo-1611591437281-460bfbe1220a?auto=format&fit=crop&w=900&q=80',
      'https://images.unsplash.com/photo-1503341455253-b2e723bb3dbb?auto=format&fit=crop&w=900&q=80',
      'https://images.unsplash.com/photo-1519681393784-d120267933ba?auto=format&fit=crop&w=900&q=80',
    ],
    sectionId: 'sec-5',
    subsectionId: 'sub-5-2',
    goldWeight: 18.0,
    makingCharge: { type: 'percentage', value: 8 },
    basePrice: 8000,
    currentPrice: 125640, // Will be calculated
    quantity: 8,
    rating: 4.7,
    reviews: 44,
    highlights: [
      'Coordinated set for everyday wear',
      'Comfortable and lightweight design',
      'Perfect for office and casual occasions',
    ],
    material: '22K Gold',
    purity: '91.6% (22K)',
    collection: 'Everyday Essentials',
    occasion: 'Daily Wear',
    specifications: {
      'Gold Weight': '18.0 g',
      'Includes': 'Necklace, Earrings, Bracelet',
      Finish: 'Polished',
      Warranty: '1 Year',
      Seller: 'Luxury Jewelry Co.',
    },
    createdAt: new Date('2024-04-20'),
    updatedAt: new Date('2024-04-20'),
  },
  {
    id: 'prod-18',
    name: 'Party Statement Set',
    description: 'A bold statement jewelry set with oversized pieces and sparkling accents, designed for parties and celebrations.',
    images: [
      'https://images.unsplash.com/photo-1529400971008-f566de0e6dfc?auto=format&fit=crop&w=900&q=80',
      'https://images.unsplash.com/photo-1503342217505-b0a15ec3261c?auto=format&fit=crop&w=900&q=80',
      'https://images.unsplash.com/photo-1541745537413-6bb6f68ba1c3?auto=format&fit=crop&w=900&q=80',
    ],
    sectionId: 'sec-5',
    subsectionId: 'sub-5-3',
    goldWeight: 22.0,
    makingCharge: { type: 'percentage', value: 13 },
    basePrice: 12000,
    currentPrice: 159430, // Will be calculated
    quantity: 4,
    rating: 4.9,
    reviews: 21,
    highlights: [
      'Bold statement pieces for parties',
      'Sparkling accents and premium craftsmanship',
      'Perfect for celebrations and special events',
    ],
    material: '22K Gold',
    purity: '91.6% (22K)',
    collection: 'Party Glamour',
    occasion: 'Party & Celebration',
    specifications: {
      'Gold Weight': '22.0 g',
      'Includes': 'Necklace, Earrings, Ring',
      'Stone Type': 'Lab-Created Gemstones',
      Warranty: '1 Year',
      Seller: 'Luxury Jewelry Co.',
    },
    createdAt: new Date('2024-04-25'),
    updatedAt: new Date('2024-04-25'),
  },
  {
    id: 'prod-19',
    name: 'Minimalist Gold Ring',
    description: 'A sleek minimalist ring in pure gold, featuring clean lines and subtle elegance for modern sensibilities.',
    images: [
      'https://images.unsplash.com/photo-1522312346375-d1a52e2b99b3?auto=format&fit=crop&w=900&q=80',
      'https://images.unsplash.com/photo-1496055417576-5af7b6d8d3d3?auto=format&fit=crop&w=900&q=80',
      'https://images.unsplash.com/photo-1515377905703-c511b6b50f4e?auto=format&fit=crop&w=900&q=80',
    ],
    sectionId: 'sec-1',
    subsectionId: 'sub-1-3',
    goldWeight: 3.0,
    makingCharge: { type: 'fixed', value: 1500 },
    basePrice: 0,
    currentPrice: 21750, // Will be calculated
    quantity: 14,
    rating: 4.6,
    reviews: 35,
    highlights: [
      'Clean minimalist design for modern style',
      'Comfortable fit for daily wear',
      'Versatile for stacking and layering',
    ],
    material: '22K Gold',
    purity: '91.6% (22K)',
    collection: 'Modern Minimal',
    occasion: 'Everyday Wear',
    specifications: {
      'Gold Weight': '3.0 g',
      Finish: 'Polished',
      Width: '3 mm',
      Warranty: '1 Year',
      Seller: 'Luxury Jewelry Co.',
    },
    createdAt: new Date('2024-05-01'),
    updatedAt: new Date('2024-05-01'),
  },
  {
    id: 'prod-20',
    name: 'Pearl Drop Earrings',
    description: 'Elegant drop earrings featuring lustrous pearls in gold settings, combining classic beauty with modern design.',
    images: [
      'https://images.unsplash.com/photo-1541745537413-6bb6f68ba1c3?auto=format&fit=crop&w=900&q=80',
      'https://images.unsplash.com/photo-1529400971008-f566de0e6dfc?auto=format&fit=crop&w=900&q=80',
      'https://images.unsplash.com/photo-1503342217505-b0a15ec3261c?auto=format&fit=crop&w=900&q=80',
    ],
    sectionId: 'sec-3',
    subsectionId: 'sub-3-2',
    goldWeight: 3.5,
    makingCharge: { type: 'percentage', value: 15 },
    basePrice: 5000,
    currentPrice: 28775, // Will be calculated
    quantity: 10,
    rating: 4.8,
    reviews: 28,
    highlights: [
      'Classic pearl design with gold elegance',
      'Lustrous pearls for timeless appeal',
      'Perfect for formal and semi-formal occasions',
    ],
    material: '22K Gold',
    purity: '91.6% (22K)',
    collection: 'Pearl Elegance',
    occasion: 'Formal & Evening',
    specifications: {
      'Gold Weight': '3.5 g',
      'Pearl Type': 'Freshwater Pearls',
      'Drop Length': '3 cm',
      Warranty: '1 Year',
      Seller: 'Luxury Jewelry Co.',
    },
    createdAt: new Date('2024-05-05'),
    updatedAt: new Date('2024-05-05'),
  },
];

// Mock Promo Codes
export const mockPromoCodes: PromoCode[] = [
  {
    id: 'promo-1',
    code: 'WELCOME10',
    description: '10% off on first purchase',
    discountType: 'percentage',
    discountValue: 10,
    minPurchase: 5000,
    maxUsage: 100,
    usedCount: 45,
    expiryDate: new Date('2025-12-31'),
    isActive: true,
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
  },
  {
    id: 'promo-2',
    code: 'GOLD2024',
    description: 'Special gold jewelry discount',
    discountType: 'percentage',
    discountValue: 15,
    minPurchase: 20000,
    maxUsage: 50,
    usedCount: 28,
    expiryDate: new Date('2024-12-31'),
    isActive: true,
    createdAt: new Date('2024-02-01'),
    updatedAt: new Date('2024-02-01'),
  },
  {
    id: 'promo-3',
    code: 'FLAT2000',
    description: 'Flat ₹2000 off on purchases above ₹50000',
    discountType: 'fixed',
    discountValue: 2000,
    minPurchase: 50000,
    usedCount: 0,
    expiryDate: new Date('2024-06-30'),
    isActive: true,
    createdAt: new Date('2024-03-01'),
    updatedAt: new Date('2024-03-01'),
  },
];

// Helper function to calculate product price based on gold price
export const calculateProductPrice = (
  product: Product,
  goldPricePerGram: number
): number => {
  const goldCost = product.goldWeight * goldPricePerGram;
  
  if (product.makingCharge.type === 'percentage') {
    const makingChargeAmount = (goldCost * product.makingCharge.value) / 100;
    return goldCost + makingChargeAmount + product.basePrice;
  } else {
    return goldCost + product.makingCharge.value + product.basePrice;
  }
};

// Function to get all products with updated prices
export const getProductsWithUpdatedPrices = (
  products: Product[],
  goldPricePerGram: number
): Product[] => {
  return products.map((product) => ({
    ...product,
    currentPrice: calculateProductPrice(product, goldPricePerGram),
  }));
};
